"""
cTrader OAuth2 token manager with automatic refresh.

Stores tokens in a local JSON file and refreshes the access token
before it expires, using the refresh token (which never expires but
is replaced on every use).

Token file location: ``<project_root>/.ctrader_tokens.json``
"""
from __future__ import annotations

import json
import logging
import time
from pathlib import Path
from typing import Optional

import requests

from live_trading.config import config

logger = logging.getLogger(__name__)

_TOKEN_FILE = Path(__file__).resolve().parents[2] / ".ctrader_tokens.json"
_REFRESH_URL = "https://openapi.ctrader.com/apps/token"

REFRESH_MARGIN_SECONDS = 3600


class CTraderTokenManager:
    """Manages cTrader access + refresh tokens with automatic renewal.

    On first run the user must supply an access token via the env var
    ``CTRADER_ACCESS_TOKEN`` *and* a refresh token via the token file
    (generated by ``get_ctrader_token.py``).  After that, the manager
    transparently refreshes tokens before they expire.
    """

    def __init__(
        self,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        token_file: Optional[Path] = None,
    ):
        self._client_id = client_id or config.CTRADER_CLIENT_ID or ""
        self._client_secret = client_secret or config.CTRADER_CLIENT_SECRET or ""
        self._token_file = token_file or _TOKEN_FILE

        self._access_token: Optional[str] = None
        self._refresh_token: Optional[str] = None
        self._expires_at: float = 0.0

        self._load()

    @property
    def access_token(self) -> str:
        """Return a valid access token, refreshing first if needed."""
        if self._is_expired():
            if self._refresh_token:
                self._do_refresh()
            else:
                logger.warning(
                    "[TOKEN] Access token expired and no refresh token available. "
                    "Re-run: python -m live_trading.scripts.get_ctrader_token"
                )
        return self._access_token or ""

    @property
    def refresh_token(self) -> Optional[str]:
        return self._refresh_token

    def has_refresh_token(self) -> bool:
        return bool(self._refresh_token)

    def force_refresh(self) -> bool:
        """Force an immediate token refresh.  Returns True on success."""
        if not self._refresh_token:
            logger.error("[TOKEN] Cannot refresh — no refresh token stored")
            return False
        return self._do_refresh()

    def store_tokens(
        self,
        access_token: str,
        refresh_token: str,
        expires_in: int = 2_628_000,
    ) -> None:
        """Persist a new token pair (called by ``get_ctrader_token`` and after refresh)."""
        self._access_token = access_token
        self._refresh_token = refresh_token
        self._expires_at = time.time() + expires_in
        self._save()
        logger.info(
            f"[TOKEN] Stored new tokens (expires in {expires_in}s / "
            f"~{expires_in // 86400} days)"
        )

    def _is_expired(self) -> bool:
        if not self._access_token:
            return True
        return time.time() >= (self._expires_at - REFRESH_MARGIN_SECONDS)

    def _do_refresh(self) -> bool:
        logger.info("[TOKEN] Refreshing access token via cTrader REST API...")
        try:
            resp = requests.get(
                _REFRESH_URL,
                params={
                    "grant_type": "refresh_token",
                    "refresh_token": self._refresh_token,
                    "client_id": self._client_id,
                    "client_secret": self._client_secret,
                },
                headers={"Accept": "application/json"},
                timeout=30,
            )
            resp.raise_for_status()
            data = resp.json()

            new_access = data.get("accessToken")
            new_refresh = data.get("refreshToken")
            expires_in = data.get("expiresIn", 2_628_000)

            if not new_access or not new_refresh:
                error = data.get("errorCode", "unknown")
                desc = data.get("description", "")
                logger.error(f"[TOKEN] Refresh failed: {error} — {desc}")
                return False

            self._access_token = new_access
            self._refresh_token = new_refresh
            self._expires_at = time.time() + expires_in
            self._save()

            logger.info(
                f"[TOKEN] Refresh successful — new token expires in "
                f"{expires_in}s (~{expires_in // 86400} days)"
            )
            return True

        except requests.RequestException as exc:
            logger.error(f"[TOKEN] HTTP refresh request failed: {exc}")
            return False

    def _load(self) -> None:
        """Bootstrap tokens from the on-disk file, falling back to env var."""
        if self._token_file.exists():
            try:
                data = json.loads(self._token_file.read_text())
                self._access_token = data.get("access_token")
                self._refresh_token = data.get("refresh_token")
                self._expires_at = data.get("expires_at", 0.0)
                logger.info(
                    f"[TOKEN] Loaded tokens from {self._token_file.name} "
                    f"(expires_at={self._expires_at:.0f})"
                )
                return
            except (json.JSONDecodeError, OSError) as exc:
                logger.warning(f"[TOKEN] Could not read {self._token_file}: {exc}")

        env_token = config.CTRADER_ACCESS_TOKEN
        if env_token:
            self._access_token = env_token
            self._expires_at = 0.0
            logger.info("[TOKEN] Using CTRADER_ACCESS_TOKEN from env (no refresh token — will expire)")

    def _save(self) -> None:
        try:
            self._token_file.write_text(json.dumps({
                "access_token": self._access_token,
                "refresh_token": self._refresh_token,
                "expires_at": self._expires_at,
            }, indent=2) + "\n")
        except OSError as exc:
            logger.error(f"[TOKEN] Could not write {self._token_file}: {exc}")


_instance: Optional[CTraderTokenManager] = None


def get_token_manager() -> CTraderTokenManager:
    """Module-level singleton."""
    global _instance
    if _instance is None:
        _instance = CTraderTokenManager()
    return _instance
